# OpenAI API Key untuk Asisten Ki Hajar
OPENAI_API_KEY = "sk-or-v1-"

# Menyimpan password admin untuk panel agregator
admin_password = ""

bank_bri_mikro_password = "password_bri"
bank_mandiri_umkm_password = "password_mandiri"
# dll.
