# OpenAI API Key untuk Asisten Ki Hajar
OPENAI_API_KEY = "sk-or-v1-"

# Menyimpan password admin untuk panel agregator
admin_password = ""

bank_bri_mikro_password = "password_bri"
bank_mandiri_umkm_password = "password_mandiri"
# dll

# Contoh konfigurasi di secrets.toml (hanya untuk sandbox, jangan commit)
BANK_API_BSS_BABEL_endpoint = "https://sandbox.bank-sumbabel.co.id/api/v1/loan"
BANK_API_BSS_BABEL_api_key = "sandbox_key_xxx"


